export const projects = [
  {
    id: 1,
    title: `Quitandas Online`,
    subtitle: 'Página estática',
    imageFront: '/images/quitanda-online-front.png',
    imageBack: '/images/quitanda-online-back.png',
    moreInfo: 'https://quitandasonline.netlify.app/',
  },
  {
    id: 2,
    title: `Recipes App`,
    subtitle: 'OverHooked',
    imageFront: '/images/app-recipes-front.png',
    imageBack: '/images/app-recipes-back.png',
    moreInfo: 'https://overhooked.netlify.app/',
  },
  {
    id: 3,
    title: `DS Vendas`,
    subtitle: 'Dashboard para análise de dados',
    imageFront: '/images/dsvendas-front.png',
    imageBack: '/images/dsvendas-back.png',
    moreInfo: 'https://dsvendas-marques.netlify.app/',
  },
  {
    id: 4,
    title: `Electrum`,
    subtitle: 'Página estática',
    imageFront: '/images/electrum-front.png',
    imageBack: '/images/electrum-back.png',
    moreInfo: 'https://github.com/renatomak/projeto-electrum',
  },
  {
    id: 5,
    title: `Online Store`,
    subtitle: 'Usando API do Mercado Livre',
    imageFront: '/images/online-store-front.png',
    imageBack: '/images/online-store-back.png',
    moreInfo: 'https://github.com/renatomak/online-store',
  },
];

export const abilities = [
  'Excel',
  'Word',
  'PowerPoint',
  'Workbench',
  'Gimp',
  'Linux',
  'Git',
  'Trello',
  'pgAdmin4',
];
export const languages = [
  'HTML',
  'CSS',
  'JavaScript',
  'React',
  'NodeJS',
  'PostgreSQL',
  'SQL',
  'MongoDB',
  'Python',
  'Java',
];
